development:
  adapter: postgresql
  database: dev_db
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test_db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: prod_db
  pool: 5
  timeout: 5000